version: '3.1'

services:
  app:
    image: node
    working_dir: /home/node/app
    entrypoint: ["npm", "run", "dev"]
    volumes:
      - .:/home/node/app
    ports:
      - "3000:8000"
    networks:
      - contracts-network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./utils:/utils
    networks:
      - contracts-network
networks:
  contracts-network:
    driver: bridge